### ISSUE TITLE
Add filter function to arrays

### ISSUE THREAD

**Issue by Frantss** [JorrenH/solid-fluent-store#1]
Hi, really like the idea, i'm testing the library out

**Problem**
I need to remove an element from an array, and with the current API there seems to be no way of achieving this.

**Expected behavior / proposed solution**
```typescript
const [read, write] = createFluentStore(['a', 'b', 'c']);

const removedElements  = write.filter(s => s === 'a');
// ^? number of elements that where removed
```
**Actual behavior**

The `.$filter` method requires allows to substitute elements, but not remove them from the array

And using a `Set` instead of an `Array` does not fit use-cases where elements can be repeated

**Alternative solution**
Add a generic `set` method

```typescript
const [read, write] = createFluentStore(['a', 'b', 'c']);

write.set(read.filter(s => s === 'a'));
```

**Comment by Frantss** [comment]
Just realized there's a generic set by doing

```typescript
const [read, write] = createFluentStore(['a', 'b', 'c']);

write(read.filter(s => s === 'a'));
```

But it get a type error since `write` is a readonly array while `read.filter(s => s === 'a')` is not

**Comment by JorrenH** [comment]
It is by design that the store writer only contains mutating methods, while the reader has access to immutable methods (like `Array.filter`). I decided to stick with the [`Array` sepcification](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Indexed_collections#array_methods) to avoid confusion in the API, and certainly wouldn't want to overload the meaning of `filter`.

As for the problem at hand your last solution is one way to approach it. For me it doesn't give a type-error though. However instead of filtering the value from the reader you may also use the following syntax:

```ts
const [read, write] = createFluentStore(['a', 'b', 'c']);

write(prev => prev.filter(s => s === 'a'));
```

Hope this clarifies my reasoning and helps with your problem.

**Comment by Frantss** [comment]
Thanks, this helps me a lot, I missed that API in the readme. Problem solved!
